### ISSUE TITLE
Bot ID 

### ISSUE THREAD

**Issue by mericausa** [Aqyl123/BotBrokerBot#1]
Hey, I love this script. Great work man! 

Bot Broker added Sole AIO today. How do I find the product ID? That may not be whats its called. Here is an example: 

https://www.botbroker.io/bots/17/chart?key_type=lifetime&days=365

Where do you find the "17" in that URL? I looked all over and inspected the website. I can't seem to find where to get that number so I can add Sole. I appreciate your help!

**Comment by Aqyl123** [comment]
Sole AIO would be Bot ID 47. You can find it by navigating to the bot's own page on BotBroker, opening Inspect Element, going to the Network Tab, selecting XHR and CTRL + R to find the file named: chart?key_type=lifetime&days=365. Upon clicking on that file you will be greeted by the Bot ID Request URL: https://botbroker.io/bots/47/chart?key_type=lifetime&days=365
